/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dashboard;

import LoginApps.Login;
import Properties.JPanelBoard;
import java.awt.Frame;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author User
 */
public class GantiPw extends javax.swing.JDialog {
    
    private JPanel content;
    private final Dashboard menuUtama;
   

    /**
     * Creates new form GantiPw
     */
    public GantiPw(Frame parent, boolean modal, Dashboard menuUtama) {
        add(new JPanelBoard());
        initComponents();
        this.menuUtama = menuUtama; 
        this.content = menuUtama.getContentPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBoard1 = new Properties.JPanelBoard();
        jPanelBoard2 = new Properties.JPanelBoard();
        lbGantiPw = new javax.swing.JLabel();
        lbTentang = new javax.swing.JLabel();
        lbKeluar = new javax.swing.JLabel();
        lbBatal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanelBoard1.setBackground(new java.awt.Color(178, 111, 96));
        jPanelBoard1.setOpaque(true);
        jPanelBoard1.setRoundBottomLeft(30);
        jPanelBoard1.setRoundBottomRight(30);
        jPanelBoard1.setRoundTopLeft(30);
        jPanelBoard1.setRoundTopRight(30);

        jPanelBoard2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBoard2.setRoundBottomLeft(30);
        jPanelBoard2.setRoundBottomRight(30);
        jPanelBoard2.setRoundTopLeft(30);
        jPanelBoard2.setRoundTopRight(30);

        lbGantiPw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGantiPw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/unlock-keyhole-solid.png"))); // NOI18N
        lbGantiPw.setText("Ganti Password");
        lbGantiPw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbGantiPw.setIconTextGap(15);
        lbGantiPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbGantiPwMouseClicked(evt);
            }
        });

        lbTentang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/circle-info-solid.png"))); // NOI18N
        lbTentang.setText("Tentang Aplikasi");
        lbTentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTentang.setIconTextGap(15);

        lbKeluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/right-from-bracket-solid.png"))); // NOI18N
        lbKeluar.setText("Keluar");
        lbKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbKeluar.setIconTextGap(15);
        lbKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbKeluarMouseClicked(evt);
            }
        });

        lbBatal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/circle-xmark-solid.png"))); // NOI18N
        lbBatal.setText("Batal");
        lbBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBatal.setIconTextGap(15);
        lbBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBatalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBoard2Layout = new javax.swing.GroupLayout(jPanelBoard2);
        jPanelBoard2.setLayout(jPanelBoard2Layout);
        jPanelBoard2Layout.setHorizontalGroup(
            jPanelBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoard2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGantiPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelBoard2Layout.setVerticalGroup(
            jPanelBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoard2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbGantiPw)
                .addGap(18, 18, 18)
                .addComponent(lbTentang)
                .addGap(18, 18, 18)
                .addComponent(lbKeluar)
                .addGap(18, 18, 18)
                .addComponent(lbBatal)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBoard1Layout = new javax.swing.GroupLayout(jPanelBoard1);
        jPanelBoard1.setLayout(jPanelBoard1Layout);
        jPanelBoard1Layout.setHorizontalGroup(
            jPanelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoard1Layout.createSequentialGroup()
                .addComponent(jPanelBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBoard1Layout.setVerticalGroup(
            jPanelBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBatalMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lbBatalMouseClicked

    private void lbKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKeluarMouseClicked
        // TODO add your handling code here:
        LogOut();
    }//GEN-LAST:event_lbKeluarMouseClicked

    private void lbGantiPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGantiPwMouseClicked
        // TODO add your handling code here:
        dispose();
        Settings set = new Settings();
        menuUtama.gantiPanel(set);
    }//GEN-LAST:event_lbGantiPwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GantiPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GantiPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GantiPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GantiPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GantiPw dialog = new GantiPw(new javax.swing.JFrame(), true,  new Dashboard());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Properties.JPanelBoard jPanelBoard1;
    private Properties.JPanelBoard jPanelBoard2;
    private javax.swing.JLabel lbBatal;
    private javax.swing.JLabel lbGantiPw;
    private javax.swing.JLabel lbKeluar;
    private javax.swing.JLabel lbTentang;
    // End of variables declaration//GEN-END:variables

    private void LogOut(){
        try {
            Object[] tombol = {"YA", "Tidak"};
            int option = JOptionPane.showOptionDialog(this, 
                    "Apakah anda ingin keluar dari aplikasi?", 
                    "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.INFORMATION_MESSAGE, null, tombol, 0);
            if (option == 0) {
                // Klik "YA" untuk keluar
                dispose(); // Menutup frame Dashboard
                Login loginFrame = new Login();
                loginFrame.setVisible(true); // Menampilkan frame Login
                JOptionPane.showMessageDialog(this, "Berhasil Keluar");
            }
        } catch (HeadlessException e) {
            // Handle exception
        }
    }
}
