/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import static Dashboard.PanelData.tblData;
import JavaPackage.Koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Laporan extends javax.swing.JPanel {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        ViewData("");
        
        
        cmbTanggal.removeAllItems();
        for(int i = 1; i <= 31; i++){
            cmbTanggal.addItem(""+i);
        }
        
        String[] namaBulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"};

        cmbBulan.removeAllItems();
        for (String bulan : namaBulan) {
            cmbBulan.addItem(bulan);
        }

        
        cmbTahun.removeAllItems();
        for(int i = 2017; i <= 2100; i++){
            cmbTahun.addItem(""+i);
        }
        
        btnFilter.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Memanggil metode filterData() saat tombol "Cetak" ditekan
            filterData();
        }
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTanggal = new javax.swing.JComboBox<>();
        cmbTahun = new javax.swing.JComboBox<>();
        cmbBulan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        scrol = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnFilter = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("pn_laporan"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 586));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 417));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 417));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 586));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN ABSENSI");

        cmbTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmbTahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        cmbBulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober ", "November", "Desember" }));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cetak");

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLaporan.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tblLaporan.setMinimumSize(new java.awt.Dimension(60, 500));
        tblLaporan.setShowGrid(true);
        scrol.setViewportView(tblLaporan);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        btnFilter.setText("FILTER");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbTanggal, 0, 152, Short.MAX_VALUE)
                                .addGap(11, 11, 11)
                                .addComponent(cmbBulan, 0, 170, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTahun, 0, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(scrol, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, "pnUtama");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        filterData();
    }//GEN-LAST:event_btnFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JComboBox<String> cmbTahun;
    private javax.swing.JComboBox<String> cmbTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane scrol;
    public static javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables

    public static void ViewData(String where) {
        Object[] kolom = {"ID","NAMA","NIP","JABATAN","JENIS KELAMIN", "SHIFT PIKET", "TANGGAL MASUK", "ALAMAT", "JAM MASUK"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        tblLaporan.setModel(model);

    //ambil data dari database
        try {
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM laporan "+where;
            ResultSet rs = st.executeQuery(sql);

            //dan tambahkan data ke dalam tabel
            while (rs.next()) {                 
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String nip = rs.getString("nip");
                String jabatan = rs.getString("jabatan");
                String jk = rs.getString("jk");
                String shiftPiket = rs.getString("shift_piket");
                String tglMasuk = rs.getString("tanggal_masuk");
                String alamat = rs.getString("alamat");
                String jamMasuk= rs.getString("jam_masuk");
                Object[] data = {id,nama,nip,jabatan,jk, shiftPiket,tglMasuk,alamat,jamMasuk};
                model.addRow(data); 
            }
        } catch (SQLException e) {
        }
    }
    
    public void filterData() {
    // Membersihkan tabel tblLaporan
        DefaultTableModel model = (DefaultTableModel) tblLaporan.getModel();
        model.setRowCount(0);

        // Mengambil data dari database berdasarkan tanggal, bulan, dan tahun yang dipilih
        try {
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();

            // Mendapatkan pilihan dari combo box
            String selectedTanggal = cmbTanggal.getSelectedItem().toString();
            String selectedBulan = cmbBulan.getSelectedItem().toString();
            String selectedTahun = cmbTahun.getSelectedItem().toString();

            // Query untuk mengambil data dari "data" dan "tabel_absensi" berdasarkan "id"
            // Query untuk mengambil data dari "data" dan "tabel_absensi" berdasarkan "id"
            String sqlData = "SELECT d.id, d.nama, d.nip, d.jabatan, d.jk, d.alamat, ta.tanggal, ta.jam_masuk, ta.shift_piket FROM data d " +
                "JOIN tabel_absensi ta ON d.id = ta.id " +
                "WHERE ta.tanggal = ?";

            PreparedStatement preparedStatement = c.prepareStatement(sqlData);
            preparedStatement.setString(1, selectedTanggal);
            preparedStatement.setString(2, selectedBulan);
            preparedStatement.setString(3, selectedTahun);


            ResultSet resultSet = preparedStatement.executeQuery();

            // Mengisi tabel tblLaporan dengan data yang ditemukan
            while (resultSet.next()) {
                String id = resultSet.getString("id");
                String nama = resultSet.getString("nama");
                String nip = resultSet.getString("nip");
                String jabatan = resultSet.getString("jabatan");
                String jk = resultSet.getString("jk");
                String alamat = resultSet.getString("alamat");
                String tanggalMasuk = resultSet.getString("tanggal");
                String jamMasuk = resultSet.getString("jam_masuk");
                String shiftPiket = resultSet.getString("shift_piket");

                String insertSql = "INSERT INTO laporan (id, nama, nip, jabatan, jk, alamat, tanggal_masuk, jam_masuk, shift_piket) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement insertStatement = c.prepareStatement(insertSql);
                insertStatement.setString(1, id);
                insertStatement.setString(2, nama);
                insertStatement.setString(3, nip);
                insertStatement.setString(4, jabatan);
                insertStatement.setString(5, jk);
                insertStatement.setString(6, alamat);
                insertStatement.setString(7, tanggalMasuk);
                insertStatement.setString(8, jamMasuk);
                insertStatement.setString(9, shiftPiket);
                insertStatement.executeUpdate();
            }

            // Tutup sumber daya
            resultSet.close();
            preparedStatement.close();
            st.close();
            c.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}
