/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import static Dashboard.PanelData.tblData;
import JavaPackage.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Laporan extends javax.swing.JPanel {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        ViewData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTanggal = new javax.swing.JComboBox<>();
        cmbTahun = new javax.swing.JComboBox<>();
        cmbBulan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        scrol = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 586));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 417));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 417));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 586));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN ABSENSI");

        cmbTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmbTahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        cmbBulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober ", "November", "Desember" }));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cetak");

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLaporan.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tblLaporan.setMinimumSize(new java.awt.Dimension(60, 500));
        tblLaporan.setShowGrid(true);
        scrol.setViewportView(tblLaporan);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbTanggal, 0, 152, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(cmbBulan, 0, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTahun, 0, 143, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrol, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, "pnUtama");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JComboBox<String> cmbTahun;
    private javax.swing.JComboBox<String> cmbTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane scrol;
    public static javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables

    public static void ViewData(String where) {
        Object[] kolom = {"ID","NAMA","NIP","JABATAN","JENIS KELAMIN","NO HP", "ALAMAT", "TANGGAL MASUK"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        tblLaporan.setModel(model);

    //ambil data dari database
        try {
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM laporan "+where;
            ResultSet rs = st.executeQuery(sql);

            //dan tambahkan data ke dalam tabel
            while (rs.next()) {                 
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String nip = rs.getString("nip");
                String jabatan = rs.getString("jabatan");
                String jk = rs.getString("jk");
                String alamat = rs.getString("alamat");
                String tanggal_masuk = rs.getString("tanggal_masuk");
                Object[] data = {id,nama,nip,jabatan,jk,alamat,tanggal_masuk};
                model.addRow(data); 
            }
        } catch (SQLException e) {
        }
    }
    
    public void filterData() {
        // Mendapatkan pilihan dari combo box
        String selectedTanggal = cmbTanggal.getSelectedItem().toString();
        String selectedBulan = cmbBulan.getSelectedItem().toString();
        String selectedTahun = cmbTahun.getSelectedItem().toString();

        // Membuat kueri SQL berdasarkan pilihan combo box
        String whereClause = " WHERE ";
        whereClause += "tanggal_masuk = '" + selectedTanggal + "' ";
        whereClause += "AND bulan = '" + selectedBulan + "' ";
        whereClause += "AND tahun = '" + selectedTahun + "' ";

        // Membersihkan tabel tblLaporan
        DefaultTableModel model = (DefaultTableModel) tblLaporan.getModel();
        model.setRowCount(0);

        // Mengambil data dari tblData1 dan tbl2 sesuai dengan kriteria
        try {
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();

            // Query untuk mengambil data dari tblData1
            String sqlData1 = "SELECT id, nama, nip, jabatan, jk, no_hp, alamat FROM tblData1" + whereClause;
            ResultSet rsData1 = st.executeQuery(sqlData1);

            // Query untuk mengambil data dari tbl2
            String sqlTbl2 = "SELECT id, nama, nip, jabatan, tanggal_masuk, jam_masuk, jam_pulang FROM tbl2" + whereClause;
            ResultSet rsTbl2 = st.executeQuery(sqlTbl2);

            // Mengisi tabel tblLaporan dengan data yang ditemukan
            while (rsData1.next()) {
                Object[] data = new Object[7];
                data[0] = rsData1.getString("id");
                data[1] = rsData1.getString("nama");
                data[2] = rsData1.getString("nip");
                data[3] = rsData1.getString("jabatan");
                data[4] = rsData1.getString("jk");
                data[5] = rsData1.getString("no_hp");
                data[6] = rsData1.getString("alamat");
                model.addRow(data);
            }

            while (rsTbl2.next()) {
                Object[] data = new Object[7];
                data[0] = rsTbl2.getString("id");
                data[1] = rsTbl2.getString("nama");
                data[2] = rsTbl2.getString("nip");
                data[3] = rsTbl2.getString("jabatan");
                data[4] = rsTbl2.getString("tanggal_masuk");
                data[5] = rsTbl2.getString("jam_masuk");
                data[6] = rsTbl2.getString("jam_pulang");
                model.addRow(data);
            }

            // Tutup sumber daya
            rsData1.close();
            rsTbl2.close();
            st.close();
            c.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


}
