/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import JavaPackage.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.text.SimpleDateFormat;

/**
 *
 * @author User
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        ViewTabelAbsensi("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAbsensi = new javax.swing.JTable();
        txtInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 387));
        setPreferredSize(new java.awt.Dimension(500, 387));
        setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABSENSI ANGGOTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAbsensi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblAbsensiKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblAbsensi);

        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/magnifying-glass-solid.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInput)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
        // TODO add your handling code here:
        checkAndInsertData();
    }//GEN-LAST:event_txtInputKeyReleased

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyTyped

    private void tblAbsensiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAbsensiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAbsensiKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblAbsensi;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables


    public static void ViewTabelAbsensi(String where) {
        Object[] kolom = {"ID","NAMA","NIP","TANGGAL", "JAM MASUK", "SHIFT PIKET"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        tblAbsensi.setModel(model);

        // Ambil data dari database
        try {
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM tabel_absensi " + where;
            ResultSet rs = st.executeQuery(sql);

            // Dan tambahkan data ke dalam tabel
            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String nip = rs.getString("nip");

                // Mengubah format tanggal dari yyyy-MM-dd menjadi dd-MM-yyyy
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String tanggal = sdf.format(rs.getDate("tanggal"));

                String jam_masuk = rs.getString("jam_masuk");
                String shift_piket = rs.getString("shift_piket");
                Object[] data = {id, nama, nip, tanggal, jam_masuk, shift_piket};
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    
    public void checkAndInsertData() {
        String nip = txtInput.getText(); // Mengambil NIP dari JTextField

        // Query untuk memeriksa apakah NIP ada dalam tblData1
        String query = "SELECT id, nama, nip, shift_piket FROM data WHERE nip = ?";

        try {
            Connection connection = Koneksi.sambungkeDB(); // Menghubungkan ke database
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, nip);

            ResultSet result = preparedStatement.executeQuery();

            if (result.next()) {
                // Data ditemukan, ambil data dari tblData1
                int id = result.getInt("id");
                String nama = result.getString("nama");
                String shift_piket = result.getString("shift_piket");

                // Ini adalah input pertama hari ini, masukkan data dengan jam_masuk
                String insertQuery = "INSERT INTO tabel_absensi (id, nama, nip, tanggal, jam_masuk, shift_piket) VALUES (?, ?, ?, CURRENT_DATE, CURRENT_TIMESTAMP,?)";
                PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
                insertStatement.setInt(1, id);
                insertStatement.setString(2, nama);
                insertStatement.setString(3, nip);
                insertStatement.setString(4, shift_piket);
                insertStatement.executeUpdate();

                ViewTabelAbsensi("");
                // Tambahkan tindakan selanjutnya di sini jika diperlukan
            } else {
                // NIP tidak ditemukan, lakukan tindakan yang sesuai
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}
