/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Dashboard;

import JavaPackage.Koneksi;
import JavaPackage.MainClass;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PanelData extends javax.swing.JPanel {
    
    
    
    
    long ID;
    MainClass mainClass;
    /**
     * Creates new form PanelData
     */
    public PanelData() {
        initComponents();
        ViewData("");
        TampilJumlahData();
        
        String[] jenisKelamin = {"Laki-Laki", "Perempuan"};

        cmbJk.removeAllItems();
        for (String JK : jenisKelamin) {
            cmbJk.addItem(JK);
        }
        String[] shiftPiket = {"1-Shift Pagi", "2-Shift Malam"};

        cmbShift.removeAllItems();
        for (String SP : shiftPiket) {
            cmbShift.addItem(SP);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainUtama = new javax.swing.JPanel();
        pn_data = new javax.swing.JPanel();
        pn_JudulData = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbLaki = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbPerempuan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn_Button = new javax.swing.JPanel();
        btnTambah = new Properties.JBtn();
        btnHapus = new Properties.JBtn();
        btnEdit = new Properties.JBtn();
        pn_tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_tambah = new javax.swing.JPanel();
        pn_JudulData1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pn_Button1 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        txtBatal = new javax.swing.JButton();
        pn_tabel1 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbJk = new javax.swing.JComboBox<>();
        cmbShift = new javax.swing.JComboBox<>();
        pn_update = new javax.swing.JPanel();
        pn_JudulData2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pn_Button2 = new javax.swing.JPanel();
        btnSimpan1 = new javax.swing.JButton();
        txtBatal1 = new javax.swing.JButton();
        pn_tabel2 = new javax.swing.JPanel();
        txtNama1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNip1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtJabatan1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNoHp1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Laki1 = new javax.swing.JRadioButton();
        Perempuan1 = new javax.swing.JRadioButton();
        txtAlamat1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Pagi1 = new javax.swing.JRadioButton();
        Malam1 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainUtama.setMinimumSize(new java.awt.Dimension(423, 417));
        mainUtama.setPreferredSize(new java.awt.Dimension(423, 417));
        mainUtama.setLayout(new java.awt.CardLayout());

        pn_data.setLayout(new java.awt.BorderLayout());

        pn_JudulData.setBackground(new java.awt.Color(255, 255, 255));
        pn_JudulData.setPreferredSize(new java.awt.Dimension(500, 80));

        jPanel1.setBackground(new java.awt.Color(178, 111, 96));
        jPanel1.setPreferredSize(new java.awt.Dimension(235, 68));

        lbLaki.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbLaki.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLaki.setText("0");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("JUMLAH ANGGOTA LAKI-LAKI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLaki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbLaki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(178, 111, 96));
        jPanel2.setPreferredSize(new java.awt.Dimension(235, 68));

        lbPerempuan.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbPerempuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerempuan.setText("0");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("JUMLAH ANGGOTA PEREMPUAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPerempuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbPerempuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(178, 111, 96));
        jPanel3.setPreferredSize(new java.awt.Dimension(235, 68));

        lbData.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbData.setText("0");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("JUMLAH TOTAL DATA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pn_JudulDataLayout = new javax.swing.GroupLayout(pn_JudulData);
        pn_JudulData.setLayout(pn_JudulDataLayout);
        pn_JudulDataLayout.setHorizontalGroup(
            pn_JudulDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JudulDataLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_JudulDataLayout.setVerticalGroup(
            pn_JudulDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JudulDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_JudulDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_data.add(pn_JudulData, java.awt.BorderLayout.PAGE_START);

        pn_Button.setBackground(new java.awt.Color(255, 255, 255));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ButtonLayout = new javax.swing.GroupLayout(pn_Button);
        pn_Button.setLayout(pn_ButtonLayout);
        pn_ButtonLayout.setHorizontalGroup(
            pn_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_ButtonLayout.setVerticalGroup(
            pn_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ButtonLayout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_data.add(pn_Button, java.awt.BorderLayout.PAGE_END);

        pn_tabel.setBackground(new java.awt.Color(255, 255, 255));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        txtSearch.setText("Pencarian...");
        txtSearch.setPreferredSize(new java.awt.Dimension(97, 22));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/magnifying-glass-solid.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA ANGGOTA");

        javax.swing.GroupLayout pn_tabelLayout = new javax.swing.GroupLayout(pn_tabel);
        pn_tabel.setLayout(pn_tabelLayout);
        pn_tabelLayout.setHorizontalGroup(
            pn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_tabelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_tabelLayout.setVerticalGroup(
            pn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_tabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pn_data.add(pn_tabel, java.awt.BorderLayout.CENTER);

        mainUtama.add(pn_data, "card2");

        pn_tambah.setLayout(new java.awt.BorderLayout());

        pn_JudulData1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TAMBAH ANGGOTA");

        javax.swing.GroupLayout pn_JudulData1Layout = new javax.swing.GroupLayout(pn_JudulData1);
        pn_JudulData1.setLayout(pn_JudulData1Layout);
        pn_JudulData1Layout.setHorizontalGroup(
            pn_JudulData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JudulData1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_JudulData1Layout.setVerticalGroup(
            pn_JudulData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JudulData1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pn_tambah.add(pn_JudulData1, java.awt.BorderLayout.PAGE_START);

        pn_Button1.setBackground(new java.awt.Color(255, 255, 255));

        btnSimpan.setBackground(new java.awt.Color(0, 102, 255));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setIconTextGap(7);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        txtBatal.setBackground(new java.awt.Color(255, 51, 51));
        txtBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBatal.setForeground(new java.awt.Color(255, 255, 255));
        txtBatal.setText("Batal");
        txtBatal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtBatal.setIconTextGap(7);
        txtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Button1Layout = new javax.swing.GroupLayout(pn_Button1);
        pn_Button1.setLayout(pn_Button1Layout);
        pn_Button1Layout.setHorizontalGroup(
            pn_Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Button1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(txtBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_Button1Layout.setVerticalGroup(
            pn_Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Button1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pn_tambah.add(pn_Button1, java.awt.BorderLayout.PAGE_END);

        pn_tabel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NIP");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Jabatan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Nomer HP");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Shift Piket");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Alamat");

        cmbJk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbShift.setPreferredSize(new java.awt.Dimension(72, 30));

        javax.swing.GroupLayout pn_tabel1Layout = new javax.swing.GroupLayout(pn_tabel1);
        pn_tabel1.setLayout(pn_tabel1Layout);
        pn_tabel1Layout.setHorizontalGroup(
            pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tabel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbJk, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(txtJabatan)
                    .addComponent(txtNip)
                    .addComponent(txtNama)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(cmbShift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pn_tabel1Layout.setVerticalGroup(
            pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tabel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNip, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbJk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pn_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37))
        );

        pn_tambah.add(pn_tabel1, java.awt.BorderLayout.CENTER);

        mainUtama.add(pn_tambah, "card2");

        pn_update.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pn_updateComponentAdded(evt);
            }
        });
        pn_update.setLayout(new java.awt.BorderLayout());

        pn_JudulData2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TAMBAH ANGGOTA");

        javax.swing.GroupLayout pn_JudulData2Layout = new javax.swing.GroupLayout(pn_JudulData2);
        pn_JudulData2.setLayout(pn_JudulData2Layout);
        pn_JudulData2Layout.setHorizontalGroup(
            pn_JudulData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JudulData2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_JudulData2Layout.setVerticalGroup(
            pn_JudulData2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JudulData2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pn_update.add(pn_JudulData2, java.awt.BorderLayout.PAGE_START);

        pn_Button2.setBackground(new java.awt.Color(255, 255, 255));

        btnSimpan1.setBackground(new java.awt.Color(0, 102, 255));
        btnSimpan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setText("Simpan");
        btnSimpan1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan1.setIconTextGap(7);
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        txtBatal1.setBackground(new java.awt.Color(255, 51, 51));
        txtBatal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBatal1.setForeground(new java.awt.Color(255, 255, 255));
        txtBatal1.setText("Batal");
        txtBatal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBatal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtBatal1.setIconTextGap(7);
        txtBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Button2Layout = new javax.swing.GroupLayout(pn_Button2);
        pn_Button2.setLayout(pn_Button2Layout);
        pn_Button2Layout.setHorizontalGroup(
            pn_Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Button2Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(txtBatal1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_Button2Layout.setVerticalGroup(
            pn_Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Button2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pn_update.add(pn_Button2, java.awt.BorderLayout.PAGE_END);

        pn_tabel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Nama");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("NIP");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Jabatan");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Jenis Kelamin");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Nomer HP");

        Laki1.setBackground(new java.awt.Color(255, 255, 255));
        Laki1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Laki1.setText("Laki-Laki");

        Perempuan1.setBackground(new java.awt.Color(255, 255, 255));
        Perempuan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Perempuan1.setText("Perempuan");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Shift Piket");

        Pagi1.setBackground(new java.awt.Color(255, 255, 255));
        Pagi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pagi1.setText("1 - Shift Pagi");

        Malam1.setBackground(new java.awt.Color(255, 255, 255));
        Malam1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Malam1.setText("2 - Shift Malam");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Alamat");

        javax.swing.GroupLayout pn_tabel2Layout = new javax.swing.GroupLayout(pn_tabel2);
        pn_tabel2.setLayout(pn_tabel2Layout);
        pn_tabel2Layout.setHorizontalGroup(
            pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tabel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(12, 12, 12)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_tabel2Layout.createSequentialGroup()
                        .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoHp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                            .addComponent(txtJabatan1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNip1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNama1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlamat1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(pn_tabel2Layout.createSequentialGroup()
                        .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_tabel2Layout.createSequentialGroup()
                                .addComponent(Laki1)
                                .addGap(18, 18, 18)
                                .addComponent(Perempuan1))
                            .addGroup(pn_tabel2Layout.createSequentialGroup()
                                .addComponent(Pagi1)
                                .addGap(18, 18, 18)
                                .addComponent(Malam1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pn_tabel2Layout.setVerticalGroup(
            pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tabel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNip1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJabatan1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Laki1)
                    .addComponent(Perempuan1))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoHp1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Pagi1)
                    .addComponent(Malam1))
                .addGap(16, 16, 16)
                .addGroup(pn_tabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(37, 37, 37))
        );

        pn_update.add(pn_tabel2, java.awt.BorderLayout.CENTER);

        mainUtama.add(pn_update, "card2");

        add(mainUtama, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalActionPerformed
        // TODO add your handling code here:
        mainUtama.removeAll();
        mainUtama.repaint();
        mainUtama.revalidate();
        
        mainUtama.add(pn_data);
        mainUtama.repaint();
        mainUtama.revalidate();
    }//GEN-LAST:event_txtBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int unusedID = getUnusedID();
        String nama = txtNama.getText();
        String nip = txtNip.getText();
        String jabatan = txtJabatan.getText();
        String jk = cmbJk.getSelectedItem().toString();
        String shift_piket = cmbShift.getSelectedItem().toString();
        String no_hp = txtNoHp.getText();
        String alamat = txtAlamat.getText();

        // Validasi input (Anda dapat menambahkan validasi sesuai kebutuhan)
        if (nama.isEmpty() || nip.isEmpty() || jabatan.isEmpty() || no_hp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        // Memasukkan data ke dalam database
        try {
            Connection c = Koneksi.sambungkeDB();
            PreparedStatement ps = c.prepareStatement("INSERT INTO data (id, nama, nip, jabatan, jk, shift_piket, no_hp, alamat) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            ps.setInt(1, unusedID);
            ps.setString(2, nama);
            ps.setString(3, nip);
            ps.setString(4, jabatan);
            ps.setString(5, jk);
            ps.setString(6, shift_piket);
            ps.setString(7, no_hp);
            ps.setString(8, alamat);

            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                // Kembali ke panel data setelah berhasil menyimpan
                mainUtama.removeAll();
                mainUtama.repaint();
                mainUtama.revalidate();
                mainUtama.add(pn_data);
                mainUtama.repaint();
                mainUtama.revalidate();
                // Memuat ulang data di tabel
                ViewData("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int index = tblData.getSelectedRow();
        if(index != -1){
            String id = tblData.getValueAt(index, 0).toString(); 
            long TheID = Long.parseLong(id);
            ID = TheID;
            
            String nama = tblData.getValueAt(index, 1).toString();
            String nip = tblData.getValueAt(index, 2).toString();
            String jabatan = tblData.getValueAt(index, 3).toString();
            String jk = tblData.getValueAt(index, 4).toString();
            String shift_piket = tblData.getValueAt(index, 5).toString();
            String no_hp = tblData.getValueAt(index, 6).toString();
            String tanggal_masuk = tblData.getValueAt(index, 7).toString();
            mainClass = new MainClass();
            mainClass.setId(id);
            mainClass.setNama(nama); 
            mainClass.setNip(nip); 
            mainClass.setJabatan(jabatan); 
            mainClass.setJk(jk);
            mainClass.setShift_piket(shift_piket);
            mainClass.setNo_hp(no_hp); 
            mainClass.setTanggal_masuk(tanggal_masuk); 
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String key = txtSearch.getText();
        String where = " WHERE "
        + "id LIKE '%" + key + "%' OR "
        + "nama LIKE '%" + key + "%' OR "
        + "nip LIKE '%" + key + "%' OR "
        + "jabatan LIKE '%" + key + "%' OR "
        + "jk LIKE '%" + key + "%' OR "
        + "no_hp LIKE '%" + key + "%' OR "
        + "alamat LIKE '%" + key + "%'";
        ViewData(where);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
        String key = txtSearch.getText();
        String where = " WHERE "
        + "id LIKE '%" + key + "%' OR "
        + "nama LIKE '%" + key + "%' OR "
        + "nip LIKE '%" + key + "%' OR "
        + "jabatan LIKE '%" + key + "%' OR "
        + "jk LIKE '%" + key + "%' OR "
        + "no_hp LIKE '%" + key + "%' OR "
        + "alamat LIKE '%" + key + "%'";
        ViewData(where);
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        mainUtama.removeAll();
        mainUtama.repaint();
        mainUtama.revalidate();
        
        mainUtama.add(pn_tambah);
        mainUtama.repaint();
        mainUtama.revalidate();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        HapusData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        mainUtama.removeAll();
        mainUtama.repaint();
        mainUtama.revalidate();
        
        mainUtama.add(pn_update);
        mainUtama.repaint();
        mainUtama.revalidate();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void txtBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatal1ActionPerformed

    private void pn_updateComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pn_updateComponentAdded
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_pn_updateComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Laki1;
    private javax.swing.JRadioButton Malam1;
    private javax.swing.JRadioButton Pagi1;
    private javax.swing.JRadioButton Perempuan1;
    private Properties.JBtn btnEdit;
    private Properties.JBtn btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private Properties.JBtn btnTambah;
    private javax.swing.JComboBox<String> cmbJk;
    private javax.swing.JComboBox<String> cmbShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbLaki;
    private javax.swing.JLabel lbPerempuan;
    private javax.swing.JPanel mainUtama;
    private javax.swing.JPanel pn_Button;
    private javax.swing.JPanel pn_Button1;
    private javax.swing.JPanel pn_Button2;
    private javax.swing.JPanel pn_JudulData;
    private javax.swing.JPanel pn_JudulData1;
    private javax.swing.JPanel pn_JudulData2;
    private javax.swing.JPanel pn_data;
    private javax.swing.JPanel pn_tabel;
    private javax.swing.JPanel pn_tabel1;
    private javax.swing.JPanel pn_tabel2;
    private javax.swing.JPanel pn_tambah;
    private javax.swing.JPanel pn_update;
    public static javax.swing.JTable tblData;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAlamat1;
    private javax.swing.JButton txtBatal;
    private javax.swing.JButton txtBatal1;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtJabatan1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtNip1;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtNoHp1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public static void ViewData(String where) {
        Object[] kolom = {"ID","NAMA","NIP","JABATAN","JENIS KELAMIN", "SHIFT PIKET","NO HP", "ALAMAT"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        tblData.setModel(model); 

    //ambil data dari database
        try {
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM data "+where;
            ResultSet rs = st.executeQuery(sql);

            //dan tambahkan data ke dalam tabel
            while (rs.next()) {                 
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                String nip = rs.getString("nip");
                String jabatan = rs.getString("jabatan");
                String jk = rs.getString("jk");
                String shift_piket = rs.getString("shift_piket");
                String no_hp = rs.getString("no_hp");
                String alamat = rs.getString("alamat");
                Object[] data = {id,nama,nip,jabatan,jk, shift_piket,no_hp,alamat};
                model.addRow(data); 
            }
        } catch (SQLException e) {
        }
    }
    
    private int getUnusedID() {
        int unusedID = -1;
        Connection c = Koneksi.sambungkeDB();
        
        try {
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("SELECT MIN(id) FROM data WHERE id NOT IN (SELECT deleted_id FROM deleted_data)");
            if (rs.next()) {
                unusedID = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        return (unusedID == -1) ? getNextAvailableID() : unusedID;
    }

    private int getNextAvailableID() {
        int nextID = -1;
        Connection c = Koneksi.sambungkeDB();
        
        try {
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(id) FROM data");
            if (rs.next()) {
                nextID = rs.getInt(1) + 1;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        return (nextID == -1) ? 1 : nextID;
    }
    
    public static void insertDeletedID(int deletedID) {
    try {
        Connection c = Koneksi.sambungkeDB();
        String insertQuery = "INSERT INTO deleted_data (deleted_id) VALUES (?)";
        PreparedStatement ps = c.prepareStatement(insertQuery);
        ps.setInt(1, deletedID);
        ps.executeUpdate();
        ps.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    
    
    private void HapusData() {
        if (ID > 0) {
            try {
                Object[] tombol = {"YA", "Tidak"};
                int option = JOptionPane.showOptionDialog(this, 
                        "Apakah anda ingin menghapus data?", 
                        "Konfirmasi", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.INFORMATION_MESSAGE, null, tombol, 0);
                if (option == 0) {
                    // Hapus data dari tabel utama
                    Connection c = Koneksi.sambungkeDB();
                    Statement st = c.createStatement();
                    String sql = "DELETE FROM data WHERE id='" + ID + "'";
                    // Eksekusi query
                    st.executeUpdate(sql);

                    // Jika data berhasil dihapus dari tabel utama, maka kita tambahkan ID ke dalam tabel deleted_data
                    if (st.getUpdateCount() > 0) {
                        insertDeletedID((int) ID);
                        // Refresh view table
                        int selectedRow = tblData.getSelectedRow();
                        ViewData("");
                        JOptionPane.showMessageDialog(this, "Data telah dihapus");
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal menghapus data");
                    }
                }                
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih Data"); 
        }
    }
    
    private void TampilJumlahData(){
        try{
            Connection c = Koneksi.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT jk, COUNT(id) FROM data GROUP BY jk";
            ResultSet rs = st.executeQuery(sql);  
            int jumlahLakiLaki = 0;
            int jumlahPerempuan = 0;

            while (rs.next()) {
                String jenisKelamin = rs.getString("jk");
                int jumlah = rs.getInt(2);

                if ("Laki-Laki".equals(jenisKelamin)) {
                    jumlahLakiLaki = jumlah;
                } else if ("Perempuan".equals(jenisKelamin)) {
                    jumlahPerempuan = jumlah;
                }
            }

            int totalData = jumlahLakiLaki + jumlahPerempuan;
            lbLaki.setText(Integer.toString(jumlahLakiLaki));
            lbPerempuan.setText(Integer.toString(jumlahPerempuan));
            lbData.setText(Integer.toString(totalData));
            
            
        }catch (SQLException e) {
            e.printStackTrace();
        }      
    }
    
    private void UpdateData() {
        try {
            String nama = txtNama1.getText();
            String nip = txtNip1.getText();
            String jabatan = txtJabatan1.getText();
            String jk = cmbJk.getSelectedItem().toString();
            String no_hp = txtNoHp1.getText(); // ID data yang akan diupdate

            if (nama.isEmpty() || nip.isEmpty() || jabatan.isEmpty() || jk.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lengkapi Data!");
            } else {
                // Persiapkan query UPDATE
                String sql = "UPDATE data SET "
                        + "nama='" + nama + "', "
                        + "nip='" + nip + "', "
                        + "jabatan='" + jabatan + "', "
                        + "jk='" + jk + "', "
                        + "no_hp='" + no_hp + "'";

                Connection c = Koneksi.sambungkeDB();
                Statement st = c.createStatement();
                st.executeUpdate(sql);

                // Refresh tampilan data
                ViewData("");
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Data GAGAL diupdate\n" + e.getMessage());
        }
    }


}
